# To run: conda env create -f environment.yml
name: nerf_tf2
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - cudatoolkit=11.0
    - tensorflow=2.8
    - numpy
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - configargparse
    - imagemagick
    - ipywidgets
    - tqdm